name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Obter o repositório
      uses: actions/checkout@v3

    - name: Configurar o Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Instalando as dependencies
      run: npm install

    - name: Rodar testes de api via controller
      run: npm run test-controller

    - name: Upload mochawesome report (controller)
      uses: actions/upload-artifact@v3
      with:
        name: mochawesome-report-controller
        path: mochawesome-report/mochawesome.html

    - name: Subir a API
      run: npm start & # Inicia a API em segundo plano
      
    - name: Esperar a API iniciar
      run: sleep 5 # Ajuste o tempo conforme necessário

    - name: Rodar testes de api via HTTP
      run: npx mocha test/external/**/*.test.js --reporter mochawesome

    - name: Upload mochawesome report
      uses: actions/upload-artifact@v4
      with:
        name: mochawesome-report
        path: mochawesome-report/mochawesome.html
